spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asdasd


logging:
  level:
    com.example.springbootmybatis.web.mapper: debug

server:
  port: 8082
#mybatis-plus:
#  mapper-locations: classpath:/mapper*/**/*.xml
#  type-aliases-package: com.example.springbootmybatis.web.po