spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asdasd
mybatis:
  type-aliases-package: com.example.springbootmybatis.web.po
  mapper-locations: classpath:/mapper*/**/*.xml


logging:
  level:
    com.example.springbootmybatis.web.mapper: debug

server:
  port: 8081